# Importando os recursos

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import cross_val_score
from tensorflow.keras import backend as k
from tensorflow.keras import utils
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer
from scikeras.wrappers import KerasClassifier

2024-08-22 15:30:38.847693: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
df = pd.read_csv('Deep Learning com Python de A a Z/Parte 1 - Redes Neurais Artificiais/classificação mais classes/iris.csv')
df.head()

sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
X = df.iloc[:, 0:4].values #todas as linhas da colunas 0 a 4, convetendo a Numpy array, pois é o formato de entrada esperado pelas redes Keras
y = df.iloc[:, 4].values #todas as linhas da coluna 5

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

# Configurando os dados

Como as redes neurais Keras recebem e retornam valores numéricos, essas strings vão ter que ser codificadas:

In [6]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Como são 3 classes, a camada de saída vai ter 3 neurônios. Ou seja, cada classe vai ser representada por uma configuração em que 1 neurônio fica bem ativo e todos os outros ficam quase inativos.<br>
Essa atividade é determinada por uma probabilidade, com 1 neurônio (que representa uma classe) sendo muito provável e todos os outros (que representam outras classes) sendo muito improváveis.<br>
Essa configuração é implementada utilizando a função Softmax.

Para representar cada classe em função de 3 neurônios:

In [7]:
y = utils.to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

Cada linha é uma amostra e cada coluna é referente à uma classe.<br>
Se tem 0, então a amostra não pertence àquela classe.<br>
Se tem 1, então pertence.

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25) #25% para teste

# Estrutura e treinamento da Rede Neural

In [9]:
def create_network():
    k.clear_session()
    network = Sequential()
    network.add(InputLayer(shape=(4,)))
    network.add(Dense(units = 4, activation = 'relu')) # units = (len(input)+len(output))/2
    network.add(Dense(units = 4, activation = 'relu'))
    network.add(Dense(units = 3, activation = 'softmax')) # camada de saída

    network.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy']) # mesmo tipo de função de perda e métrica, mas pra multiclasse
    return network

In [10]:
network = create_network()

In [11]:
network.fit(X_train, y_train, batch_size = 10, epochs=1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - categorical_accuracy: 0.6550 - loss: 0.8250
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7222 - loss: 0.6996 
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6755 - loss: 0.6724 
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.7049 - loss: 0.6031 
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.7180 - loss: 0.5552 
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.6767 - loss: 0.5492 
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - categorical_accuracy: 0.7280 - loss: 0.5012
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7466 - loss: 0.4825 
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.6986 - loss: 0.5047 
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.7169 - loss: 0.4539 
Epoch 11/10

# Analisando a precisão da Rede

In [12]:
predictions = network.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


In [13]:
predictions

array([[9.9115214e-06, 9.9945247e-01, 5.3755869e-04],
       [5.4996312e-06, 9.9665040e-01, 3.3440052e-03],
       [1.3817483e-06, 9.9973476e-01, 2.6382337e-04],
       [3.6856858e-09, 3.5404376e-04, 9.9964595e-01],
       [9.9999934e-01, 2.5445647e-07, 3.7491063e-07],
       [2.0960718e-07, 7.2993513e-04, 9.9926996e-01],
       [4.2509663e-07, 1.5157883e-02, 9.8484170e-01],
       [1.7455352e-05, 9.8642921e-01, 1.3553393e-02],
       [5.7468956e-06, 9.7510552e-01, 2.4888830e-02],
       [7.8906123e-06, 9.7195745e-01, 2.8034518e-02],
       [2.0964084e-05, 9.8619866e-01, 1.3780390e-02],
       [4.4680091e-06, 1.5075640e-01, 8.4923923e-01],
       [9.9997729e-01, 1.6660566e-05, 6.0142997e-06],
       [2.0204147e-10, 2.7403829e-07, 9.9999970e-01],
       [9.9999911e-01, 3.9100178e-07, 5.3311561e-07],
       [4.2117881e-06, 9.9218416e-01, 7.8116790e-03],
       [3.3123845e-06, 9.9556518e-01, 4.4314968e-03],
       [3.8766275e-06, 9.9954373e-01, 4.5227591e-04],
       [9.9999982e-01, 4.787

Cada valor é a probabilidade da amostra representada por aquela lista ser da respectiva classe.<br>
Para obtermos a classificação mais provável para cada amostra:

In [14]:
predictions = predictions > 0.5
predictions

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [Fa

In [15]:
y_test

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

Para convertermos cada amostra numa codificação mais simples da classe mais provável:

In [16]:
y_test2 = [np.argmax(i) for i in y_test]
y_test2

[1,
 1,
 1,
 2,
 0,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 2,
 0,
 1,
 0,
 2,
 0,
 1,
 2,
 2,
 0,
 0,
 1]

In [17]:
predictions = [np.argmax(i) for i in predictions]
predictions

[1,
 1,
 1,
 2,
 0,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 2,
 0,
 1,
 0,
 2,
 0,
 1,
 2,
 2,
 0,
 0,
 1]

Agora, para termos a precisão exata das previsões:

In [18]:
accuracy = accuracy_score(y_test2, predictions)
accuracy

0.9736842105263158

In [19]:
conf_matrix = confusion_matrix(y_test2, predictions)
print('(0)setosa  (1)versicolor  (2)virginica')
conf_matrix

(0)setosa  (1)versicolor  (2)virginica


array([[11,  0,  0],
       [ 0, 17,  1],
       [ 0,  0,  9]])

Apenas 1 erro ocorreu, que foi a classificação de uma versicolor em viginica

Alternativamente, pode-se utilizar o método de evaluação padrão da rede neural:

In [20]:
network.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - categorical_accuracy: 0.9720 - loss: 0.0521  


[0.051320649683475494, 0.9736841917037964]

# Aplicando Cross Validation

In [21]:
network2 = KerasClassifier(model = create_network, epochs = 250, batch_size=10)

In [22]:
results = cross_val_score(estimator = network2, X=X, y=y, cv = 10, scoring='accuracy')

Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - categorical_accuracy: 0.3606 - loss: 1.0908
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.3932 - loss: 1.0812
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.3229 - loss: 1.0890
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.3886 - loss: 1.0710
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - categorical_accuracy: 0.3858 - loss: 1.0663
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - categorical_accuracy: 0.3681 - loss: 1.0647
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3239 - loss: 1.0752 
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3407 - loss: 1.0575 
Epoch 9/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.3931 - loss: 1.0449  
Epoch 10/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3703 - loss: 1.0431 
Epoch 11/250
14/14 ━━━━

In [23]:
results.mean()

0.8533333333333333

In [25]:
results.std()

0.29181424837652387

In [26]:
results

array([1.        , 1.        , 1.        , 1.        , 0.86666667,
       0.93333333, 0.        , 0.93333333, 0.8       , 1.        ])