# AULA 21

## Criação de arrays

In [2]:
import numpy as np

In [2]:
lista0 = [1,2,3]

In [27]:
vetor0 = np.array(lista0) #transforma a lista0 em vetor (array 1-d) e põe na variável vetor0

In [26]:
vetor0

array([1, 2, 3])

In [16]:
lst_de_lst0 = [[1,2,3],[4,5,6],[7,8,9]] #cria uma lista de listas (matriz 2-d)

In [17]:
matriz0 = np.array(lst_de_lst0) #cria uma matriz de Numpy a partir da lista de listas

In [18]:
matriz0

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
vetor1 = np.arange(0, 10, 2.5) #função arange cria um vetor a partir de parâmetros de range

In [29]:
vetor1

array([0. , 2.5, 5. , 7.5])

In [30]:
vetor2 = np.zeros(5) #cria um vetor com 5 elementos zerados

In [31]:
vetor2

array([0., 0., 0., 0., 0.])

In [19]:
matriz1 = np.zeros((3,3)) #cria uma matriz 3x3 com elementos nulos

In [20]:
matriz1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
matriz2 = np.ones((4,4)) #cria uma matriz 4x4 com elementos unitários

In [22]:
matriz2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
matriz3 = np.eye(5) #cria uma matriz identidade 5x5

In [24]:
matriz3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
vetor3 = np.linspace(0, 10, 3) #cria um vetor com 3 numeros de 0 a 10 igualmente espaçados (dist uniforme)

In [33]:
vetor3

array([ 0.,  5., 10.])

In [71]:
vetor4 = np.random.rand(4) #função rand da sub biblioteca random cria vetor com 4 floats aleatórios entre 0 e 1

In [42]:
vetor4

array([0.23343104, 0.50538296, 0.87791251, 0.68936542])

In [43]:
matriz4 = np.random.rand(3,6) #aqui, rand foi usado para criar uma matriz 3x6 com floats aleatórios entre 0 e 1

In [44]:
matriz4

array([[0.46737717, 0.6714632 , 0.2494883 , 0.36224233, 0.23568814,
        0.03483292],
       [0.92468593, 0.346204  , 0.06399789, 0.91623935, 0.54235248,
        0.55844617],
       [0.04417353, 0.41885957, 0.58079249, 0.35632324, 0.73829439,
        0.97669907]])

In [47]:
vetor5 = np.random.rand(9) * 100 #cria vetor com 9 floats de 0 a 100

In [46]:
vetor5

array([60.13750526, 92.46749307, 23.33264955, 73.89408899, 92.01898325,
        9.97230358, 10.0993406 , 11.95305508, 20.33322773])

In [62]:
vetor6 = np.random.randn(4) #função que cria um vetor com 4 floats de 0 a 1 com média 0 e desvio padrão 1 (dist gaussiana)

In [50]:
vetor6

array([ 0.0425265 , -1.06400799, -0.07108308,  0.98680721])

In [51]:
matriz5 = np.random.randn(3,4) #cria matriz 3x4 com floats de 0 a 1 com dist gaussiana

In [52]:
matriz5

array([[-1.15050254,  0.27367573, -0.67338791, -1.41469515],
       [-1.62729428, -0.09508694, -0.18763319,  0.10509135],
       [ 1.64466061, -1.19811276, -0.61065314,  0.84740673]])

In [61]:
vetor7 = np.random.randint(2, 89, 21) #função cria um vetor com 21 inteiros aleatórios entre 2 e 89

In [56]:
vetor7

array([80, 81, 28, 61, 81, 81, 83, 15, 56,  8, 57, 29, 44, 38, 19, 72, 45,
       43,  8, 84, 37])

In [59]:
vetor8 = np.round(np.random.rand(8)*100, 0) #arredonda os resultados da rand para 0 casas decimais

In [60]:
vetor8

array([55., 26., 52., 63., 79., 19., 18.,  5.])

#### Modificando dimensões de arrays

In [64]:
vetor8 = vetor8.reshape(2,4) #método que altera as dimensões de um array

In [65]:
vetor8

array([[55., 26., 52., 63.],
       [79., 19., 18.,  5.]])

In [66]:
vetor8.shape #atributo que contém a dimensão do array para consulta

(2, 4)

#### Máximos e mínimos

In [67]:
vetor8.max() #método que retorna o maior valor contido no array

79.0

In [68]:
vetor8.min() #método que retorna o menor valor contido no array

5.0

In [69]:
vetor8.argmax() #método que retorna o índice do maior elemento do array

4

In [73]:
vetor8.argmin() #método que retorna o índice do menor elemetno do array

7

# AULA 22

## Obtendo e manipulando slices de arrays

### Vetores

In [74]:
vetor0 = np.arange(0, 50, 3)

In [75]:
vetor0

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [76]:
vetor0[4:9] #retorna um subarray com os elementos e índice 4 até 9 (sem incluir o de 9)

array([12, 15, 18, 21, 24])

In [77]:
vetor0[:4] #se o limite inferior é deixado vazio, o interpretador começa no 0

array([0, 3, 6, 9])

In [78]:
vetor0[6:] #se o limite superior é deixado vazio, o interpretador vai até o final

array([18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [79]:
vetor0[4:7] = 1000 #os elementos no range de 4 a 7 são alterados para 1000

In [80]:
vetor0

array([   0,    3,    6,    9, 1000, 1000, 1000,   21,   24,   27,   30,
         33,   36,   39,   42,   45,   48])

### Matrizes

In [84]:
matriz0 = np.random.randint(0, 50, 30).reshape(5, 6)

In [85]:
matriz0

array([[ 3, 38, 10, 40, 42, 40],
       [ 4,  0, 23, 39, 47,  1],
       [34,  0, 14, 20, 30, 37],
       [32, 36, 34, 46,  4, 18],
       [39, 20,  0, 43,  5, 39]])

In [95]:
matriz0[0:4, 0:2] #o primeiro colchetes determina o range das linhas e o segundo das colunas

array([[ 3, 38],
       [ 4,  0],
       [34,  0],
       [32, 36]])

In [97]:
matriz0[:, 0: 3]

array([[ 3, 38, 10],
       [ 4,  0, 23],
       [34,  0, 14],
       [32, 36, 34],
       [39, 20,  0]])

In [98]:
matriz0[2:4, :3] = -1 #modifica os elementos especificados no range para -1

In [99]:
matriz0

array([[ 3, 38, 10, 40, 42, 40],
       [ 4,  0, 23, 39, 47,  1],
       [-1, -1, -1, 20, 30, 37],
       [-1, -1, -1, 46,  4, 18],
       [39, 20,  0, 43,  5, 39]])

In [100]:
matriz1 = matriz0[:3, 4:] #cria um novo array usando o anterior como blueprint

In [101]:
matriz1

array([[42, 40],
       [47,  1],
       [30, 37]])

In [102]:
matriz1[:,:] = -1

matriz0

A alteração na matriz1 afetou a matriz0, pois matriz1 é apenas uma referência a uma parte de matriz0
Para criar uma matriz independente a partir de outra, usa-se o método copy:

In [105]:
matriz2 = matriz0[2:, :4].copy()

In [106]:
matriz2[:,:] = -2

In [107]:
matriz0

array([[ 3, 38, 10, 40, -1, -1],
       [ 4,  0, 23, 39, -1, -1],
       [-1, -1, -1, 20, -1, -1],
       [-1, -1, -1, 46,  4, 18],
       [39, 20,  0, 43,  5, 39]])

Percebe-se que os valores da submatriz matriz0[2:, :4] não foram alterados para -2

Essa mesma lógica vale para vetores.

### Utilizando valores booleanos como regra

In [109]:
matriz3 = np.random.randint(0, 100, 50).reshape(5, 10)

In [110]:
matriz3

array([[58, 43,  0, 44, 87, 27, 76,  9, 93, 71],
       [10, 64, 85, 14, 78, 99, 88, 51, 80, 95],
       [43, 10, 27, 78, 78, 51, 47, 28, 13, 96],
       [69, 16, 33, 20, 87,  2, 84, 73, 25, 57],
       [ 4,  6, 56, 20, 88, 18, 23, 26, 18, 68]])

In [112]:
matriz4 = matriz3 > 30 #matriz 4 será uma matriz de booleanos indicando se cada elemento de matriz3 é > 30

In [113]:
matriz4

array([[ True,  True, False,  True,  True, False,  True, False,  True,
         True],
       [False,  True,  True, False,  True,  True,  True,  True,  True,
         True],
       [ True, False, False,  True,  True,  True,  True, False, False,
         True],
       [ True, False,  True, False,  True, False,  True,  True, False,
         True],
       [False, False,  True, False,  True, False, False, False, False,
         True]])

In [114]:
vetor0 = matriz3[matriz4]

A matriz4 (de booleanos) é usada como regra para criar um vetor com valores de matriz3 com correspondentes True em matriz4.

Repare que ambas as matrizes precisam ter as mesmas dimensões, o mesmo vale para vetores.

In [115]:
vetor0

array([58, 43, 44, 87, 76, 93, 71, 64, 85, 78, 99, 88, 51, 80, 95, 43, 78,
       78, 51, 47, 96, 69, 33, 87, 84, 73, 57, 56, 88, 68])

In [117]:
vetor1 = matriz3[matriz3 % 2 == 0] #vetor1 terá os elementos pares da matriz3

In [118]:
vetor1

array([58,  0, 44, 76, 10, 64, 14, 78, 88, 80, 10, 78, 78, 28, 96, 16, 20,
        2, 84,  4,  6, 56, 20, 88, 18, 26, 18, 68])

# AULA 22

### Operações array com array

In [15]:
vetor0 = np.random.randint(0, 100, 10)

In [4]:
vetor1 = np.random.randint(0, 100, 10)

In [16]:
vetor0

array([81, 20, 79, 84,  0, 64,  8, 11, 92, 19])

In [17]:
vetor1

array([41,  7, 37, 37, 14, 73, 67, 82, 30, 90])

In [18]:
vetor0 / vetor1 #vai dividir os elementos de vetor0 pelos indexamente correspondentes em vetor1

array([1.97560976, 2.85714286, 2.13513514, 2.27027027, 0.        ,
       0.87671233, 0.11940299, 0.13414634, 3.06666667, 0.21111111])

Repare que ambos os arrays precisam ser da mesma dimensão

In [19]:
vetor1[0] = 0

In [20]:
vetor0 / vetor1

/tmp/ipykernel_5083/2638117183.py:1: RuntimeWarning: divide by zero encountered in divide
  vetor0 / vetor1


array([       inf, 2.85714286, 2.13513514, 2.27027027, 0.        ,
       0.87671233, 0.11940299, 0.13414634, 3.06666667, 0.21111111])

Na operação dos elementos de index 0, uma divisão por 0 retorna o limite (infinito). Se fosse uma operação pura de Python, retornaria um erro.

In [21]:
vetor0[0] = 0

In [22]:
vetor0/vetor1

/tmp/ipykernel_5083/2120413327.py:1: RuntimeWarning: invalid value encountered in divide
  vetor0/vetor1


array([       nan, 2.85714286, 2.13513514, 2.27027027, 0.        ,
       0.87671233, 0.11940299, 0.13414634, 3.06666667, 0.21111111])

Agora, como é uma divisão de 0 por 0, o limite não é definido, então o valor retornado é NaN (not a number)

#### Além da divisão, as outras operações aritméticas também podem ser realizadas entre arrays de mesma dimensão:

In [23]:
vetor0 * vetor1

array([   0,  140, 2923, 3108,    0, 4672,  536,  902, 2760, 1710])

In [24]:
vetor0 + vetor1

array([  0,  27, 116, 121,  14, 137,  75,  93, 122, 109])

In [26]:
vetor0 - vetor1

array([  0,  13,  42,  47, -14,  -9, -59, -71,  62, -71])

In [27]:
vetor0 ** vetor1

array([                   1,           1280000000,  2364181474413977999,
                          0,                    0,                    0,
                          0,  7505899001923557433,  1152921504606846976,
       -7248465516859801911])

### Operações array com escalar

In [29]:
vetor0 / 10 #vai retornar um array com os elementos de vetor0 divididos por 10

array([0. , 2. , 7.9, 8.4, 0. , 6.4, 0.8, 1.1, 9.2, 1.9])

In [30]:
10 / vetor0 #vai retornar um array com 10 dividido por cada elemento de vetor0

/tmp/ipykernel_5083/4110624827.py:1: RuntimeWarning: divide by zero encountered in divide
  10 / vetor0 #vai retornar um array com 10 dividido por cada elemento de vetor0


array([       inf, 0.5       , 0.12658228, 0.11904762,        inf,
       0.15625   , 1.25      , 0.90909091, 0.10869565, 0.52631579])

O mesmo que antes acontece na divisão por 0

#### Todas as outras operações aritméticas também podem ser realizadas entre array e escalar, em qualquer ordem:

In [31]:
vetor0 * 10

array([  0, 200, 790, 840,   0, 640,  80, 110, 920, 190])

In [32]:
10 ** vetor0

array([                   1,  7766279631452241920,                    0,
                          0,                    1,                    0,
                  100000000,         100000000000,                    0,
       -8446744073709551616])

In [33]:
vetor0 - 10

array([-10,  10,  69,  74, -10,  54,  -2,   1,  82,   9])

### Outras operações matemáticas disponível para arrays Numpy:

In [34]:
np.sqrt(vetor0) #retorna um array com as raízes quadradas dos elementos de vetor0

array([0.        , 4.47213595, 8.88819442, 9.16515139, 0.        ,
       8.        , 2.82842712, 3.31662479, 9.59166305, 4.35889894])

In [35]:
np.exp(vetor0) #retorna o número Euler elevado a cada elementos de vetor0

array([1.00000000e+00, 4.85165195e+08, 2.03828107e+34, 3.02507732e+36,
       1.00000000e+00, 6.23514908e+27, 2.98095799e+03, 5.98741417e+04,
       9.01762841e+39, 1.78482301e+08])

In [36]:
np.mean(vetor0) #retorna a média aritmética dos elementos de vetor0

37.7

In [37]:
np.std(vetor0) #retorna o desvio padrão dos elementos de vetor0

35.48253091311272

In [38]:
np.sin(vetor0) #retorna o seno de cada elemento de vetor0

array([ 0.        ,  0.91294525, -0.44411267,  0.73319032,  0.        ,
        0.92002604,  0.98935825, -0.99999021, -0.77946607,  0.14987721])

In [39]:
np.cos(vetor0) #retorna o cosseno de cada elemento de vetor0

array([ 1.        ,  0.40808206, -0.89597095, -0.6800235 ,  1.        ,
        0.39185723, -0.14550003,  0.0044257 , -0.62644445,  0.98870462])

In [40]:
np.max(vetor0) #outra forma de obter o maior elemento num array

92

In [41]:
np.min(vetor0) #outra forma de obter o menor elemento num array

0

#### Há dezenas de outras funções lógicas e matemáticas disponíveis para arrays Numpy, que podem ser verificadas na documentação da biblioteca.